### ISSUE TITLE
research: allow IBC packet handler to obtain and reflect what accounts were provided

### ISSUE THREAD

**Issue by dzmitry-lahoda** [ComposableFi/emulated-light-client#110]
for each program call this IBC packet handler would do based 

on https://github.com/ComposableFi/composable-ibc/issues/455

each program and SUBprogram,

so packet can call some SUBprograms

**Comment by dzmitry-lahoda** [comment]
@dhruvja when Solana program calls other program, is it correct that it should provide all accounts as parameters to subprogram called as inputs to ensure subpogram can access accounts?

**Comment by dzmitry-lahoda** [comment]
https://docs.solana.com/developing/programming-model/calling-between-programs

`invoke_signed` 

IBC calls A and A call B.

Could are send all `accounts` in invoke_signed to B as it received from IBC or it should provide only subset needed by B?

**Comment by dhruvja** [comment]
> @dhruvja when Solana program calls other program, is it correct that it should provide all accounts as parameters to subprogram called as inputs to ensure subpogram can access accounts?

Yes thats right, we need to pass all the accounts while calling a subprogram.

**Comment by dhruvja** [comment]
> https://docs.solana.com/developing/programming-model/calling-between-programs
> 
> `invoke_signed`
> 
> IBC calls A and A call B.
> 
> Could are send all `accounts` in invoke_signed to B as it received from IBC or it should provide only subset needed by B?

It should only send the accounts needed by B, sending additional accounts would just be waste.

**Comment by dzmitry-lahoda** [comment]
waste is ok up to some.

but must be order of accounts in vector be same order as in called program? 

if that is case, need filter out only needed accounts in right order. 

i am asking because need to express somd interpretation of swaps, each swap calling some pool with its own accounts. so from all accounts passed to program, some how contract doing swaps must select only needed account.

tbh i am not sure how to solve it.

**Comment by dzmitry-lahoda** [comment]
i guess that to be researched at some point.

so i am pretty sure that for any building on top of ibc on solana (any app or middleware), needs account discovery simulation.

**Comment by dzmitry-lahoda** [comment]
may be the  case each swap to be separate packet, so relayer will provide only its accounts. basically doing ibc batching. 

or relayer must be cvm aware, and parse cvm program, and form accounts for each cvm instructions.

both solution are same. question is if we do more ibc or cvm in relayer

**Comment by dhruvja** [comment]
Yes, the program expects the 

> waste is ok up to some.
> 
> but must be order of accounts in vector be same order as in called program?
> 
> if that is case, need filter out only needed accounts in right order.
> 
> i am asking because need to express somd interpretation of swaps, each swap calling some pool with its own accounts. so from all accounts passed to program, some how contract doing swaps must select only needed account.
> 
> tbh i am not sure how to solve it.

Yes, the program expects the program in an order. But if we use anchor ( given that the other program is written with the same ), it uses structs to pass the accounts and does the ordering by itself. But if we use native solana program, then we need to make sure the programs are in the order the program expects. 

In native solana program, you pass a vector of accounts and identify each of them by their index. So if you dont pass it in the same order, it would be a mess. But if u pass more accounts than it expects, it doesnt matter because u dont touch them anyways.

**Comment by dzmitry-lahoda** [comment]
alternative to find out what accounts to filter and give to called program on chain does not look cheap or tractable.

**Comment by dhruvja** [comment]
> i guess that to be researched at some point.
> 
> so i am pretty sure that for any building on top of ibc on solana (any app or middleware), needs account discovery simulation.

while passing the instruction, we can send a mapping of accounts and pass them accordingly?

**Comment by dzmitry-lahoda** [comment]
sure, how one would build mapping?

**Comment by dhruvja** [comment]
but the question is, would we know which accounts to pass before calling the program from client?

**Comment by dzmitry-lahoda** [comment]
can maintain registry of programs with the registry of abi calls, that is easy.

**Comment by dhruvja** [comment]
can u give me an example please on what use case we are talking about?

**Comment by dzmitry-lahoda** [comment]
Will dicuss I guess on friday with @blasrodri if will pick 1 or 2 contracts on solana and hardcode their invocation on sender side.

**Comment by blasrodri** [comment]
> Will dicuss I guess on friday with @blasrodri if will pick 1 or 2 contracts on solana and hardcode their invocation on sender side.

sounds good

**Comment by dzmitry-lahoda** [comment]
So closing for now. So let align on all pros and cons on Friday.
