### ISSUE TITLE
feat: defi stake security

### ISSUE THREAD

**Issue by dzmitry-lahoda** [ComposableFi/emulated-light-client#112]
Full IBC clients (no emulated) use stakes of hosts chains to secure bridge.

In case of emulated light client it is not secured by host chain stakes.

One can consult DeFi on hosted chain and limit bridges amounts per block to be some small multiple (super secure is 1 to 1) of total light client staked amount against all bridges tokens.

https://composableprotocol.slack.com/archives/C05V4GP5HMY/p1699973161006209

In this case it will prevent light client validator to drain bridge as they will not get much more than total staked.

So if they will break bridge and sell tokens, the price of their staked bridge token will go to zero as they unlock.

To smooth experience ideal solution is mana based rate limiter with amount of tokens weighted by price

No value tokens do not influence limiter at all. 

But if they start to have on chain TWAP price, they increase overall bridge per block capacity

**Comment by blasrodri** [comment]
It's important to communicate that this is secured with restaked assets. However, it's permission-less, so that anybody can stake and secure the bridge. There's no gated group of _attesters_.

**Comment by dzmitry-lahoda** [comment]
If restaked amount is less than bridged and predicted APR, there is initiative is rug bridge via bad votes.

**Comment by dzmitry-lahoda** [comment]
I just saying that in case of real IBC, bridge security protected by whole big Stake of chain host. It is trust less. Minus governance (that is already clear how to solve)

**Comment by dzmitry-lahoda** [comment]
With emulated light client there is no assumption that host chain is protecting anything. Making IBC emulated light client more like Axelar or Wormhole. Trustful bridge.

**Comment by dzmitry-lahoda** [comment]
> It's important to communicate that this is secured with restaked assets. However, it's permission-less, so that anybody can stake and secure the bridge. There's no gated group of attesters.

Neither in Axelar or in rollups.

**Comment by dzmitry-lahoda** [comment]
I imagine hacker. It stakes 2/3% of staked amount. Approve some "bad blocks". And gets of one side of tokens our.

If stake amount is 10x cheaper than bridges - he gets 9x more tokens.

That does no happen with true IBC (you have to hack host chain for that, making ALSO the tokens bridges to cost nothing).

**Comment by dzmitry-lahoda** [comment]
So the difference is that after 2/3 attack in case of real bridge, bridge(unescrowed) tokens cost nothing because whole host chain was rugged.

While in case of emulated, they still cost something as these are that chain tokens. 

In emulated it way easy to hack profitably as tokens hacker gets cost something because host chain was not rugged.

**Comment by blasrodri** [comment]
I mean, the incentive also exists in normal chains with low market cap

**Comment by dzmitry-lahoda** [comment]
on lower stake chains one cannot hack higher stake chain on ibc. bridge goes down with side a counterparty.

there is no such connection in this ibc impl. actually it is more like axelar/wormhole. 

it is not trustless anymore.

anyway, just hinting that bridge is not really trustless until the way to bind escrowed tokens to stake at leas 1 to 1.

**Comment by blasrodri** [comment]
The solution is to attract as much stake as possible. And to do rate limit. And have a delay period where fisherman can act.

**Comment by dzmitry-lahoda** [comment]
Dicussed on research meeting. In theory kind of show number showing incetive to rug bridge, in theory depending of staked vs escrowed, and staker revienew, this parameter can be indicated to user how it is his own risk to be rugged via over transfer of under staked bridge.
