### ISSUE TITLE
feat: ics20 transfer from solana (hope you will check that amount was really eascrowed)

### ISSUE THREAD

**Issue by dzmitry-lahoda** [ComposableFi/emulated-light-client#126]
https://github.com/ComposableFi/emulated-light-client/blob/f0027e180e8a59beacdc5c6f263b8d4ed44f3995/solana/solana-ibc/programs/solana-ibc/src/transfer/impls.rs#L23

**Comment by dhruvja** [comment]
The implementation of the transfer is in this PR. There are some validation pending, but the execution of transfer is here.

#72

**Comment by dhruvja** [comment]
> https://github.com/ComposableFi/emulated-light-client/blob/f0027e180e8a59beacdc5c6f263b8d4ed44f3995/solana/solana-ibc/programs/solana-ibc/src/transfer/impls.rs#L23

I think if the escrowing fails, the program would panic as of now ( which needs to be changed and return an error instead ). But maybe we can also add an assert to check if the amount was escrowed or not. WDYT?

**Comment by dzmitry-lahoda** [comment]
it seems account per second per denom, so it will check seems.
