### ISSUE TITLE
Don’t require counterpart and sequence info in send_packet

### ISSUE THREAD

**Issue by mina86** [ComposableFi/emulated-light-client#152]
Currently send_packet takes Packet as an argument.  This means that
caller has to know not only port and channel identifiers on our side
but also provide counterparty information and sequence number.  This,
however, makes no sense.

For counterparty information, it makes no sense because then we fetch
that information ourselves to figure out if it’s correct.  How about,
we just populate that information ourselves instead?

For sequence number this is actually a bug since it causes competing
send packet requests to clash.  If next squence number is 42 and two
users want to send a packet, only one of them will be accepted.
Again, instead of requiring user to send that information, fill it
ourselves.

The prototype of the send_packet method should read something like:

```rust
pub fn send_packet<'a, 'info>(
    ctx: Context<'a, 'a, 'a, 'info, SendPacket<'info>>,
    port_id: ibc::PortId,
    channel_id: u32,
    data: Vec<u8>,
    timeout_height: ibc::TimeoutHeight,
    timeout_timestamp: u64,
) -> Result<()>;
```

**Comment by blasrodri** [comment]
Good points

**Comment by dhruvja** [comment]
The `port_id` and `channel_id` would be of the source chain right?
